### PR TITLE
Lookup Sygnal version using the correct name

### LINKED ISSUE #354: `sygnal.__version__` is broken
```

dmr on titan in /tmp/env via 🐍 v3.11.6 (env) 
2023-11-21 15:27:55 ✔  $ pip install git+https://github.com/matrix-org/sygnal@v0.12.0
Collecting git+https://github.com/matrix-org/sygnal@v0.12.0
  Cloning https://github.com/matrix-org/sygnal (to revision v0.12.0) to /tmp/pip-req-build-7zt2796r
  Running command git clone --filter=blob:none --quiet https://github.com/matrix-org/sygnal /tmp/pip-req-build-7zt2796r
  Running command git checkout -q 564b751f55b695c2ab2fef7cf24ead0fb87aa550
  Resolved https://github.com/matrix-org/sygnal to commit 564b751f55b695c2ab2fef7cf24ead0fb87aa550
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aioapns<2.1,>=1.10
  Using cached aioapns-2.0.2.tar.gz (9.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting attrs>=19.2.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting cryptography>=2.6.1
  Using cached cryptography-41.0.5-cp37-abi3-manylinux_2_28_x86_64.whl (4.4 MB)
Collecting idna>=2.8
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting jaeger-client>=4.0.0
  Using cached jaeger-client-4.8.0.tar.gz (87 kB)
  Preparing metadata (setup.py) ... done
Collecting matrix-common==1.0.0
  Using cached matrix_common-1.0.0-py3-none-any.whl (7.7 kB)
Collecting opentracing>=2.2.0
  Using cached opentracing-2.4.0.tar.gz (46 kB)
  Preparing metadata (setup.py) ... done
Collecting prometheus-client<0.8,>=0.7.0
  Using cached prometheus_client-0.7.1.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Collecting py-vapid>=1.7.0
  Using cached py-vapid-1.9.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pyOpenSSL>=17.5.0
  Using cached pyOpenSSL-23.3.0-py3-none-any.whl (58 kB)
Collecting pywebpush>=1.13.0
  Using cached pywebpush-1.14.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting pyyaml>=5.1.1
  Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
Collecting sentry-sdk>=0.10.2
  Using cached sentry_sdk-1.36.0-py2.py3-none-any.whl (249 kB)
Collecting service-identity>=18.1.0
  Using cached service_identity-23.1.0-py3-none-any.whl (12 kB)
Collecting Twisted>=19.7
  Using cached twisted-23.10.0-py3-none-any.whl (3.2 MB)
Collecting zope.interface>=4.6.0
  Using cached zope.interface-6.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (249 kB)
Collecting h2>=4.0.0
  Using cached h2-4.1.0-py3-none-any.whl (57 kB)
Collecting pyjwt>=2.0.0
  Using cached PyJWT-2.8.0-py3-none-any.whl (22 kB)
Collecting cffi>=1.12
  Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (464 kB)
Collecting threadloop<2,>=1
  Using cached threadloop-1.0.2.tar.gz (4.9 kB)
  Preparing metadata (setup.py) ... done
Collecting thrift
  Using cached thrift-0.16.0.tar.gz (59 kB)
  Preparing metadata (setup.py) ... done
Collecting tornado>=4.3
  Using cached tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
Collecting http-ece>=1.1.0
  Using cached http_ece-1.1.0.tar.gz (4.9 kB)
  Preparing metadata (setup.py) ... done
Collecting requests>=2.21.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting six>=1.15.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting certifi
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting urllib3>=1.26.11
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting pyasn1
  Using cached pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
Collecting pyasn1-modules
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Collecting automat>=0.8.0
  Using cached Automat-22.10.0-py2.py3-none-any.whl (26 kB)
Collecting constantly>=15.1
  Using cached constantly-23.10.4-py3-none-any.whl (13 kB)
Collecting hyperlink>=17.1.1
  Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Collecting incremental>=22.10.0
  Using cached incremental-22.10.0-py2.py3-none-any.whl (16 kB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Requirement already satisfied: setuptools in ./lib64/python3.11/site-packages (from zope.interface>=4.6.0->matrix-sygnal==0.12.0) (65.5.1)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting hyperframe<7,>=6.0
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting hpack<5,>=4.0
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Building wheels for collected packages: matrix-sygnal, aioapns
  Building wheel for matrix-sygnal (pyproject.toml) ... done
  Created wheel for matrix-sygnal: filename=matrix_sygnal-0.12.0-py3-none-any.whl size=54041 sha256=a6b40c769d826b9a245897fa97f6950d633d904734668619946b359ad9165694
  Stored in directory: /tmp/pip-ephem-wheel-cache-75e7uwi7/wheels/26/4f/05/3e8e7c50f2ec2b5e8dbb3849d7955a86c1df426e5e74e9ce46
  Building wheel for aioapns (pyproject.toml) ... done
  Created wheel for aioapns: filename=aioapns-2.0.2-py3-none-any.whl size=8942 sha256=6c4c33063e9f3dfb88e426f077501fe420bee0f0dad6fca319a374709b4af2b6
  Stored in directory: /home/dmr/.cache/pip/wheels/68/95/8e/67ac1fe1dcfa4d930ba79dbb1379c6b1e18cda759ec92308da
Successfully built matrix-sygnal aioapns
Installing collected packages: prometheus-client, opentracing, incremental, zope.interface, urllib3, typing-extensions, tornado, six, pyyaml, pyjwt, pycparser, pyasn1, idna, hyperframe, hpack, constantly, charset-normalizer, certifi, attrs, thrift, threadloop, sentry-sdk, requests, pyasn1-modules, matrix-common, hyperlink, h2, cffi, automat, Twisted, jaeger-client, cryptography, service-identity, pyOpenSSL, py-vapid, http-ece, pywebpush, aioapns, matrix-sygnal
  DEPRECATION: prometheus-client is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for prometheus-client ... done
  DEPRECATION: opentracing is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for opentracing ... done
  DEPRECATION: thrift is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for thrift ... done
  DEPRECATION: threadloop is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for threadloop ... done
  DEPRECATION: jaeger-client is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for jaeger-client ... done
  DEPRECATION: py-vapid is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for py-vapid ... done
  DEPRECATION: http-ece is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for http-ece ... done
  DEPRECATION: pywebpush is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pywebpush ... done
Successfully installed Twisted-23.10.0 aioapns-2.0.2 attrs-23.1.0 automat-22.10.0 certifi-2023.11.17 cffi-1.16.0 charset-normalizer-3.3.2 constantly-23.10.4 cryptography-41.0.5 h2-4.1.0 hpack-4.0.0 http-ece-1.1.0 hyperframe-6.0.1 hyperlink-21.0.0 idna-3.4 incremental-22.10.0 jaeger-client-4.8.0 matrix-common-1.0.0 matrix-sygnal-0.12.0 opentracing-2.4.0 prometheus-client-0.7.1 py-vapid-1.9.0 pyOpenSSL-23.3.0 pyasn1-0.5.1 pyasn1-modules-0.3.0 pycparser-2.21 pyjwt-2.8.0 pywebpush-1.14.0 pyyaml-6.0.1 requests-2.31.0 sentry-sdk-1.36.0 service-identity-23.1.0 six-1.16.0 threadloop-1.0.2 thrift-0.16.0 tornado-6.3.3 typing-extensions-4.8.0 urllib3-2.1.0 zope.interface-6.1

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

dmr on titan in /tmp/env via 🐍 v3.11.6 (env) took 18s 
2023-11-21 15:28:59 ✔  $ pip list
Package            Version
------------------ ----------
aioapns            2.0.2
attrs              23.1.0
Automat            22.10.0
certifi            2023.11.17
cffi               1.16.0
charset-normalizer 3.3.2
constantly         23.10.4
cryptography       41.0.5
h2                 4.1.0
hpack              4.0.0
http-ece           1.1.0
hyperframe         6.0.1
hyperlink          21.0.0
idna               3.4
incremental        22.10.0
jaeger-client      4.8.0
matrix-common      1.0.0
matrix-sygnal      0.12.0
opentracing        2.4.0
pip                22.3.1
prometheus-client  0.7.1
py-vapid           1.9.0
pyasn1             0.5.1
pyasn1-modules     0.3.0
pycparser          2.21
PyJWT              2.8.0
pyOpenSSL          23.3.0
pywebpush          1.14.0
PyYAML             6.0.1
requests           2.31.0
sentry-sdk         1.36.0
service-identity   23.1.0
setuptools         65.5.1
six                1.16.0
threadloop         1.0.2
thrift             0.16.0
tornado            6.3.3
Twisted            23.10.0
typing_extensions  4.8.0
urllib3            2.1.0
zope.interface     6.1

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip

dmr on titan in /tmp/env via 🐍 v3.11.6 (env) 
2023-11-21 15:29:05 ✔  $ python
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sygnal import __version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name '__version__' from 'sygnal' (/tmp/env/lib64/python3.11/site-packages/sygnal/__init__.py)
>>> import sygnal
>>> sygnal.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sygnal' has no attribute '__version__'
```

### PR DESCRIPTION
**Pull request by DMRobertson**
We passed it a module name [1] instead of the "distribution name"(?)

Broken in 0ced8bda3c759b1584d327205245162da64488a4, so Sygnal 0.5.0.

[1]: https://docs.python.org/3/reference/import.html#name__

Fixes #354.

### CODE REVIEW

File: sygnal/__init__.py [hunk 1]
```diff
@@ -16,7 +16,7 @@
 from importlib.metadata import PackageNotFoundError, version
 
 try:
-    __version__ = version(__name__)
+    __version__ = version("matrix-sygnal")
```
Comment (clokep) [inline sygnal/__init__.py:19]: Because it is `matrix-sygnal`, not `sygnal`?

Comment (DMRobertson) [reply sygnal/__init__.py:19]: Precisely:

```
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sygnal
>>> sygnal.__name__
'sygnal'
>>> 

```

**Review by clokep — APPROVED** [review]
